// lib/bot-blocklist/tokens.ts
//
// Source of truth for the middleware bot block-list. Mirrors the two
// `Disallow: /` groups in `public/robots.txt` (training crawlers +
// autonomous AI agents). Edit this file when you edit `public/robots.txt`,
// and vice versa — there is no auto-sync.
//
// All `value` fields MUST be lowercase. The matcher lowercases each request's
// User-Agent header once before checking.

export type BlockToken =
  | { value: string; kind: 'substring' }
  | { value: string; kind: 'word-boundary' };

export type BlockGroup = 'training' | 'agent';

export const TRAINING_CRAWLER_TOKENS: readonly BlockToken[] = [
  { value: 'ai2bot', kind: 'substring' },
  { value: 'ai2bot-deepresearcheval', kind: 'substring' },
  { value: 'ai2bot-dolma', kind: 'substring' },
  { value: 'aihitbot', kind: 'substring' },
  { value: 'amazonbot', kind: 'substring' },
  { value: 'amazon-kendra', kind: 'substring' },
  { value: 'anthropic-ai', kind: 'substring' },
  { value: 'applebot-extended', kind: 'substring' },
  { value: 'bedrockbot', kind: 'substring' },
  { value: 'brightbot', kind: 'substring' },
  { value: 'bytespider', kind: 'substring' },
  { value: 'ccbot', kind: 'substring' },
  { value: 'chatglm-spider', kind: 'substring' },
  { value: 'claudebot', kind: 'substring' },
  { value: 'claude-web', kind: 'substring' },
  { value: 'cloudvertexbot', kind: 'substring' },
  { value: 'cohere-training-data-crawler', kind: 'substring' },
  { value: 'cotoyogi', kind: 'word-boundary' },
  { value: 'crawl4ai', kind: 'substring' },
  { value: 'crawlspace', kind: 'substring' },
  { value: 'datenbank crawler', kind: 'substring' },
  { value: 'deepseekbot', kind: 'substring' },
  { value: 'diffbot', kind: 'substring' },
  { value: 'echobot bot', kind: 'substring' },
  { value: 'echoboxbot', kind: 'substring' },
  { value: 'facebookbot', kind: 'substring' },
  { value: 'factset_spyderbot', kind: 'substring' },
  { value: 'firecrawlagent', kind: 'substring' },
  { value: 'friendlycrawler', kind: 'substring' },
  { value: 'google-cloudvertexbot', kind: 'substring' },
  { value: 'google-extended', kind: 'substring' },
  { value: 'googleother', kind: 'substring' },
  { value: 'googleother-image', kind: 'substring' },
  { value: 'googleother-video', kind: 'substring' },
  { value: 'gptbot', kind: 'substring' },
  { value: 'iaskbot', kind: 'substring' },
  { value: 'iaskspider', kind: 'substring' },
  { value: 'icc-crawler', kind: 'substring' },
  { value: 'imagesiftbot', kind: 'substring' },
  { value: 'imagespider', kind: 'substring' },
  { value: 'img2dataset', kind: 'substring' },
  { value: 'isscyberriskcrawler', kind: 'substring' },
  { value: 'kangaroo bot', kind: 'substring' },
  { value: 'klaviyoaibot', kind: 'substring' },
  { value: 'kunatocrawler', kind: 'substring' },
  { value: 'laion-huggingface-processor', kind: 'substring' },
  { value: 'laiondownloader', kind: 'substring' },
  { value: 'lcc', kind: 'word-boundary' },
  { value: 'linguee bot', kind: 'substring' },
  { value: 'meta-externalagent', kind: 'substring' },
  { value: 'meta-webindexer', kind: 'substring' },
  { value: 'mycentralaiscraperbot', kind: 'substring' },
  { value: 'netestate imprint crawler', kind: 'substring' },
  { value: 'omgili', kind: 'substring' },
  { value: 'omgilibot', kind: 'substring' },
  { value: 'openai', kind: 'word-boundary' },
  { value: 'pangubot', kind: 'substring' },
  { value: 'panscient', kind: 'substring' },
  { value: 'petalbot', kind: 'substring' },
  { value: 'poseidon research crawler', kind: 'substring' },
  { value: 'qualifiedbot', kind: 'substring' },
  { value: 'quillbot', kind: 'substring' },
  { value: 'sbintuitionsbot', kind: 'substring' },
  { value: 'scrapy', kind: 'substring' },
  { value: 'semrushbot-ocob', kind: 'substring' },
  { value: 'semrushbot-swa', kind: 'substring' },
  { value: 'shapbot', kind: 'substring' },
  { value: 'sidetrade indexer bot', kind: 'substring' },
  { value: 'spider', kind: 'word-boundary' },
  { value: 'terracotta', kind: 'substring' },
  { value: 'thinkbot', kind: 'substring' },
  { value: 'tiktokspider', kind: 'substring' },
  { value: 'timpibot', kind: 'substring' },
  { value: 'velenpublicwebcrawler', kind: 'substring' },
  { value: 'wardbot', kind: 'substring' },
  { value: 'webzio-extended', kind: 'substring' },
  { value: 'wpbot', kind: 'substring' },
  { value: 'wrtnbot', kind: 'substring' },
  { value: 'yak', kind: 'word-boundary' },
  { value: 'yandexadditional', kind: 'substring' },
  { value: 'yandexadditionalbot', kind: 'substring' },
  { value: 'youbot', kind: 'substring' },
  { value: 'zanistabot', kind: 'substring' },
];

export const AUTONOMOUS_AGENT_TOKENS: readonly BlockToken[] = [
  { value: 'amazonbuyforme', kind: 'substring' },
  { value: 'amzn-searchbot', kind: 'substring' },
  { value: 'andibot', kind: 'substring' },
  { value: 'anomura', kind: 'word-boundary' },
  { value: 'awario', kind: 'substring' },
  { value: 'azureai-searchbot', kind: 'substring' },
  { value: 'bigsur.ai', kind: 'substring' },
  { value: 'buddybot', kind: 'substring' },
  { value: 'channel3bot', kind: 'substring' },
  { value: 'chatgpt agent', kind: 'substring' },
  { value: 'devin', kind: 'word-boundary' },
  { value: 'googleagent-mariner', kind: 'substring' },
  { value: 'novaact', kind: 'substring' },
  { value: 'operator', kind: 'word-boundary' },
  { value: 'tavilybot', kind: 'substring' },
  { value: 'twinagent', kind: 'substring' },
];

export const BLOCKED_BOT_TOKENS: readonly BlockToken[] = [
  ...TRAINING_CRAWLER_TOKENS,
  ...AUTONOMOUS_AGENT_TOKENS,
];

// Lowercase `value` → group. Populated alongside the arrays above.
export const BLOCKED_BOT_GROUPS: Readonly<Record<string, BlockGroup>> = {
  ai2bot: 'training',
  'ai2bot-deepresearcheval': 'training',
  'ai2bot-dolma': 'training',
  aihitbot: 'training',
  amazonbot: 'training',
  'amazon-kendra': 'training',
  'anthropic-ai': 'training',
  'applebot-extended': 'training',
  bedrockbot: 'training',
  brightbot: 'training',
  bytespider: 'training',
  ccbot: 'training',
  'chatglm-spider': 'training',
  claudebot: 'training',
  'claude-web': 'training',
  cloudvertexbot: 'training',
  'cohere-training-data-crawler': 'training',
  cotoyogi: 'training',
  crawl4ai: 'training',
  crawlspace: 'training',
  'datenbank crawler': 'training',
  deepseekbot: 'training',
  diffbot: 'training',
  'echobot bot': 'training',
  echoboxbot: 'training',
  facebookbot: 'training',
  factset_spyderbot: 'training',
  firecrawlagent: 'training',
  friendlycrawler: 'training',
  'google-cloudvertexbot': 'training',
  'google-extended': 'training',
  googleother: 'training',
  'googleother-image': 'training',
  'googleother-video': 'training',
  gptbot: 'training',
  iaskbot: 'training',
  iaskspider: 'training',
  'icc-crawler': 'training',
  imagesiftbot: 'training',
  imagespider: 'training',
  img2dataset: 'training',
  isscyberriskcrawler: 'training',
  'kangaroo bot': 'training',
  klaviyoaibot: 'training',
  kunatocrawler: 'training',
  'laion-huggingface-processor': 'training',
  laiondownloader: 'training',
  lcc: 'training',
  'linguee bot': 'training',
  'meta-externalagent': 'training',
  'meta-webindexer': 'training',
  mycentralaiscraperbot: 'training',
  'netestate imprint crawler': 'training',
  omgili: 'training',
  omgilibot: 'training',
  openai: 'training',
  pangubot: 'training',
  panscient: 'training',
  petalbot: 'training',
  'poseidon research crawler': 'training',
  qualifiedbot: 'training',
  quillbot: 'training',
  sbintuitionsbot: 'training',
  scrapy: 'training',
  'semrushbot-ocob': 'training',
  'semrushbot-swa': 'training',
  shapbot: 'training',
  'sidetrade indexer bot': 'training',
  spider: 'training',
  terracotta: 'training',
  thinkbot: 'training',
  tiktokspider: 'training',
  timpibot: 'training',
  velenpublicwebcrawler: 'training',
  wardbot: 'training',
  'webzio-extended': 'training',
  wpbot: 'training',
  wrtnbot: 'training',
  yak: 'training',
  yandexadditional: 'training',
  yandexadditionalbot: 'training',
  youbot: 'training',
  zanistabot: 'training',
  amazonbuyforme: 'agent',
  'amzn-searchbot': 'agent',
  andibot: 'agent',
  anomura: 'agent',
  awario: 'agent',
  'azureai-searchbot': 'agent',
  'bigsur.ai': 'agent',
  buddybot: 'agent',
  channel3bot: 'agent',
  'chatgpt agent': 'agent',
  devin: 'agent',
  'googleagent-mariner': 'agent',
  novaact: 'agent',
  operator: 'agent',
  tavilybot: 'agent',
  twinagent: 'agent',
};
