name: Tests
on:
  push:
  pull_request:
permissions:
  contents: read
concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - run: pnpm i --frozen-lockfile
        env:
          CI: true
      - run: pnpm run test:ci
